version: "2"

networks:
  sssm:
    external: true

services:
  rabbit:
    image: rabbitmq:3.8-management
    container_name: sssm-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - sssm
